[package]
name = "uidcrc"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"

[lib]
path = "lib.rs"

[[example]]
name = "findtest"
path = "findtest.rs"

[dependencies]
hex = "0.4"
